#!/bin/sh
# Simple sandbox with bubblewrap
# Tweak it to make it more or less strict

# Note: ssh is annoying. A false ssh_conf does the trick
cat >/tmp/ssh_conf<<EOF
Host *
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
    RequestTTY yes
EOF
# Agents share a common /tmp/llme_venv with the host
bwrap --unshare-all --share-net \
	--new-session \
	--die-with-parent \
	--ro-bind / / \
	--dev /dev \
	--proc /proc \
	--tmpfs /tmp \
	--bind /tmp/llme_venv /tmp/llme_venv \
	--tmpfs /home \
	--bind /tmp/ssh_conf /etc/ssh/ssh_config \
	--bind "$PWD" "$PWD" \
	--clearenv \
	--setenv USER "$USER" \
	--setenv PATH "$PATH" \
	--setenv TERM "$TERM" \
	--setenv HOME "$PWD" \
	--chdir "$PWD"  \
	bash -c "test -f /tmp/llme_venv/bin/activate && . /tmp/llme_venv/bin/activate; $*"
